@startuml
skinparam classAttributeIconSize 0
abstract class Handler {
    +handlerRequest()
    +setNextHandler(Handler)
}
class ConcreteHandler {
}
Client -> Handler
Handler <|-- ConcreteHandler
Handler -> Handler:+successor
@enduml